#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

function autoCommitChanges() {
    printf "${HUSKY} ${GREEN} Saving $1 \n ${NC}";
    changes=`git diff --name-only HEAD $1 | wc -l`;
    if [[ $changes -ne 0 ]]; then
        git add $1
        git commit -m "AUTOMATIC-COMMIT: $2 FILES: $1"
    fi
}

function undoChanges() {
    printf "${HUSKY} ${GREEN} Undoing changes in $1 \n ${NC}";
    git fetch; git checkout origin/master -- $1
    autoCommitChanges $1 UNDO
}
donothing(){ :; }

printf "${HUSKY} ${GREEN} Making sure that the files: [${SHOULDNT_CHANGE}] has no changes ...${NC} \n";
changes=`git diff --name-only origin/master $SHOULDNT_CHANGE | wc -l`;
printf "${changes}"
if [[ $changes -ne 0 ]]; then
    printf "${HUSKY} ${YELLOW} WARNING! git detected changes in: \n";
    printf "$(git diff --name-only $SHOULDNT_CHANGE) \n ";

    printf  "Are you sure you want to add those changes  ${NC}?";
       read -p " [Y/N]" yn
            case $yn in
            [Yy]* )     donothing ;;
            [Nn]* ) undoChanges $SHOULDNT_CHANGE ;;
            * ) echo "Please answer [Y/N]";;
            esac
 
fi


printf "${HUSKY} ${GREEN} making sure ${REQUIREMENTS} is updated ...\n ${NC} "

$PIP freeze > $REQUIREMENTS
changes=`git diff --name-only HEAD $REQUIREMENTS | wc -l`;

if [ $changes -ne 0 ]; then
    autoCommitChanges ${REQUIREMENTS} update
fi
