#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"
PIP=.env/Scripts/pip.exe
REQUIREMENTS=requirements.txt

echo updating $REQUIREMENTS...
$PIP freeze > $REQUIREMENTS
git add requirements.txt
git commit -m "AUTOMATIC COMMIT: UPDATE requirements.txt"